spring.application.name=cruid_cars


spring.datasource.url=jdbc:mysql://localhost:3306/cruid_cars
spring.datasource.username=SEU_USUARIO
spring.datasource.password=SUA_SENHA

api.security.token.secret=${JWT_SECRET:my-secret-key}